### PR TITLE
Fix #244, fix docker build

### LINKED ISSUE #244: Cannot launch the CLI: `AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'`
**Describe the bug**
When launching the CLI, the following error is thrown:
```
Traceback (most recent call last):
  File "/Users/mmv/.pyenv/versions/3.10.12/bin/safe-cli", line 5, in <module>
    from safe_cli.main import main
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/site-packages/safe_cli/main.py", line 37, in <module>
    args = parser.parse_args()
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2082, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2038, in consume_positionals
    take_action(action, args)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1927, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2462, in _get_values
    value = self._get_value(action, arg_string)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2495, in _get_value
    result = type_func(arg_string)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 70, in to_checksummed_ethereum_address
    return Web3.toChecksumAddress(address)
AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'. Did you mean: 'to_checksum_address'?
```

**To Reproduce**
1. Install the cli `pip install safe-cli`
2. Launche the cli `safe-cli <address> <rpc_url>`

**Expected behavior**
The cli launches fine and useable.

**Additional context**
OS - MacOS 13.5
Python - 3.10.12

### PR DESCRIPTION
**Pull request by ptqa**
Also fixed Dockerfile otherwise it was complaining `When using COPY with more than one source file, the destination must be a directory and end with a / `

### CODE REVIEW

**Comment by ptqa** [comment]
I have read the CLA Document and I hereby sign the CLA

File: Dockerfile [hunk 1]
```diff
@@ -2,6 +2,6 @@ FROM python:3.10-alpine
 
 WORKDIR /app/
 RUN apk add build-base
-COPY setup.* README.md .
+COPY setup.* README.md /app/
```
Comment (Uxio0) [inline Dockerfile:5]:
```suggestion
COPY setup.* README.md ./
```

**Review by Uxio0 — APPROVED** [review]
I cannot reproduce this, it's working on docker `v24.0.5`, either way your PR looks good and I will merge it

**Comment by Uxio0** [comment]
Thank you for your contribution!
